config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  devise_scope :user do
   post '/users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  resources :users
  resources :mountains do
    collection do
      get 'search'
    end
  end
  resources :users, only: [:index, :show]
  resources :mountains, only: [:index, :show, :create] do
    resources :likes, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :mountain
  belongs_to :user
  validates_uniqueness_of :mountain_id, scope: :user_id
end

app/models/mountain.rb
class Mountain < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :likes
  has_many :liked_users, through: :likes, source: :user
  
  
  validates :name, presence: true
  validates :season, presence: true
  validates :start, presence: true
  validates :endtime, presence: true
  validates :food, presence: true
  validates :water, presence: true
  validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :mountains, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  
  validates :email, presence: true
  validates :encrypted_password, presence: true
  validates :username, presence: true
  
  def self.guest 
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.username = "ゲスト"
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
      # 例えば name を入力必須としているならば， user.name = "ゲスト" なども必要
    end
  end
  
  def already_liked?(mountain)
    self.likes.exists?(mountain_id: mountain.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_q_for_mountain
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
  
  def set_q_for_mountain
    @q_header = Mountain.ransack(params[:q])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(mountain_id: params[:mountain_id])
    redirect_back(fallback_location: root_path)
  end
  
  def destroy
    @like = Like.find_by(mountain_id: params[:mountain_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/mountains_controller.rb
class MountainsController < ApplicationController
  
    before_action :authenticate_user!
  
  def index
    @mountains = Mountain.all
  end

  def show
    @mountain = Mountain.find(params[:id])
    @user = User.find_by(id: current_user.id)
    @like = Like.new
  end

  def new
    @mountain = Mountain.new
    
  end
  
  def create
    @mountain = Mountain.new(mountain_params)
    @mountain.user_id = current_user.id
    if @mountain.invalid?
      flash[:notice] = "項目を全部入力してください"
      render "new"
    else
    @mountain.save
    flash[:notice] = "山を登録しました"
    redirect_to @mountain
    end
  end
  
  def destroy
    @mountain = Mountain.find(params[:id])
    @mountain.destroy
    flash[:notice] = "投稿を削除しました"
    redirect_to :mountains
  end
  
  def search
    @q = Mountain.ransack(params[:q])
    @mountains = @q.result(distinct: true)
    if @q_header
      @mountains = @q_header.result(distinct: true)
    end
  end

  def edit
  end
  
  private
  def set_q
    @q = Mountain.ransack(params[:q])
  end
  
  def mountain_params
    params.require(:mountain).permit(:content, :name, :season, :start, :endtime, :food, :water, :image)
  end
end

app/controllers/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
 before_action :ensure_normal_user, only: %i[update destroy]

  def ensure_normal_user
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーの更新・削除はできません。'
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
 before_action :ensure_normal_user, only: %i[update destroy]

  def ensure_normal_user
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーの更新・削除はできません。'
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user = User.update(user_params)
    redirect_to user_path(@user)
  end
  
  private
  def user_params
    params.require(:user).permit(:username, :email, :profile_image, :profile)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/mountains_helper.rb
module MountainsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<section class="wrapper">
  <div class="container">
    <div class="content">
      <h2 class="heading">GO TO MOUNTAINとは</h2>
      <p>気になる山の情報をシェアできるサービスです</p>
      <p>
        <%= search_form_for @q_header, url: search_mountains_path do |f| %>
        <%= f.search_field :name_cont, placeholder: "山の名前" %>
        <%= f.submit "山検索" %>
        <% end %>
       </p>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gotomountain</title>
      <meta name="viewport" content="width=device-width,initial-scale=1">
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <% if flash[:notice] %>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    <header>  
      <nav class="navbar is-primary">
        <div class="navbar-brand">
          <%= link_to root_path, class: "navbar-item" do %>
            <h1 class="title is-3" style="font-family: cursive;">GO TO MOUNTAIN</h1>
          <% end %>
        </div>
        <div class="header-right">
          <% if user_signed_in? %>
            <div class="hidden_box">
              <label for="label1">メニュー</label>
                <input type="checkbox" id="label1"/>
                  <ul class="hidden_show" >
                    <li><%= link_to "登った山登録", new_mountain_path %></li>
                    <li><%= link_to "登録済み山一覧", :mountains%></li>
                    <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "lbutton is-warning is-light" %></li>
                  </ul>
            </div>
            <% else %>
            <div class="hidden_box">
              <label for="label1">メニュー</label>
                <input type="checkbox" id="label1"/>
                  <ul class="hidden_show" >
                    <li> <%= link_to "ログイン", new_user_session_path, class: "lbutton is-warning is-light" %></li>
                    <li><%= link_to "新規登録", new_user_registration_path, class: "lbutton is-warning is-light" %></li>
                    <li><%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: "post" %></li>
                  </ul>
            </div>
           <% end %> 
        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>

app/views/mountains/edit.html.erb
<h1>Mountains#edit</h1>
<p>Find me in app/views/mountains/edit.html.erb</p>

app/views/mountains/index.html.erb
<% if flash[:notice] %>
  <p class="notice"><%= flash[:notice] %></p>
<% end %>

<section class="section">
  <div class="container">
    <h1 class="title is-3">登録一覧</h1>
    <div class="columns is-multiline">
      <% @mountains.each do |mountain| %>
        <div class="column is-3">
          <div class="card">
            <div class="card-content">
              <div class="card-image">
                <figure class="image">
                  <%= link_to mountain_path(mountain) do %>
                    <%= image_tag mountain.image if mountain.image.present? %>
                  <% end %>
                </figure>
              </div>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <div class="title"><%=link_to mountain.name, mountain_path(mountain) %></div>
                </div>
              </div>
              <div class="media">
                <div class="media-content">
                  <div class="title"><%=link_to mountain.season, mountain_path(mountain) %></div>
                </div>
              </div>
            </div>
          </div>
        </div>
        (<%= mountain.liked_users.count %>)
      <% end %>
    </div>
  </div>
</section>

app/views/mountains/new.html.erb
<section class="topwrapper">
  <div class="container">
    <div class="content">
      <h1 class="heading">山登録</h1>
        <%= form_for @mountain do |f| %>
        <table>
          <tr>
　  　　    <th><%= f.label :山の名前 %></th>
            <td><%= f.text_field :name %></td>
          </tr>
          
          <tr>
            <th><%= f.label :季節 %></th>
            <td><%= f.text_field :season %></td>
          </tr>
          
          <tr>
            <th><%= f.label :頂上までの時間 %></th>
            <td><%= f.time_field :start %></td>
          </tr>
          
          <tr>
            <th><%= f.label :食べ物 %></th>
            <td><%= f.number_field :food %>食分</td>
          </tr>
          
          <tr>
            <th><%= f.label :水分 %></th>
            <td><%= f.number_field :water %>リットル</td>
          </tr>
          
          <tr>
            <th><%= f.label :山の写真 %></th>
            <td><%= f.file_field :image %></td>
          </tr>
        
            <p><%= f.submit "登録完了する", class:  "button is-success"%></p>

          </table>
          <% end %>
        </div>
    </div>
</section>

app/views/mountains/search.html.erb
<head>
    <title>Places Search Box</title>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
    <link rel="stylesheet" type="text/css" href="../stylesheet/text.css" />
    <script src="../javasclipt/map.js"></script>
  </head>
  <body>
    <input
      id="pac-input"
      class="controls"
      type="text"
      placeholder="Search Box"
    />
    <div id="map"></div>

    <!-- Async script executes immediately and must be after any DOM elements used in callback. -->
    <script
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCQKp3g-slof3FTN3YY8rN8HLxmPcUmWQc&libraries=places&libraries=places&v=initMap"
      async
    ></script>
  </body>
<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @mountains.each do |mountain| %>
        <div class="column is-3">
          <div class="card">
            <div class="card-content">
              <div class="card-image">
                <figure class="image">
                  <%= link_to mountain_path(mountain) do %>
                    <%= image_tag mountain.image if mountain.image.present? %>
                  <% end %>
                </figure>
              </div>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <div class="title"><%=link_to mountain.name, mountain_path(mountain) %></div>
                </div>
              </div>
              <div class="media">
                <div class="media-content">
                  <div class="title"><%=link_to mountain.season, mountain_path(mountain) %></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/mountains/show.html.erb
<div class="complete">
  <table border="1">
   <thead>
    <tr>
      <th>山の画像</th>
      <th>山の名前</th>
      <th>季節</th>
      <th>頂上までの時間</th>
      <th>食べ物</th>
      <th>水分</th>
    </tr>
   </thead>
   <tbody>
    <tr>
      <td><%= image_tag @mountain.image if @mountain.image.present? %></td>
      <td><%= @mountain.name %></td>
      <td><%= @mountain.season %></td>
      <td><%= @mountain.start.to_s(:datetime_jp) %></td>
      <td><%= @mountain.food %>食分</td>
      <td><%= @mountain.water %>リットル</td>
    </tr>
   </tbody> 
  </table>
  <h3>いいね件数: <%= @mountain.likes.count %></h3>
<% if current_user.already_liked?(@mountain) %>
  <%= button_to 'いいねを取り消す', mountain_like_path(@mountain), method: :delete %>
<% else %>
  <%= button_to 'いいね', mountain_likes_path(@mountain) %>
<% end %>
</div>

app/views/users/edit.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        編集
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
　　    <%= form_for @user do |f| %>
          <div class="field">
            <%= f.label :ユーザーネーム, class: "label" %>
            <%= f.text_field :username, class: "input" %>
          </div>
          <div class="field">
            <%= f.label :メールアドレス, class: "label" %>
            <%= f.text_field :email, class: "input" %>
          </div>
          <div class="field">
            <%= f.label :プロフィール, class: "label" %>
            <%= f.text_area :profile, class: "textarea" %>
          </div>
          <div class="field">
            <%= f.label :プロフィール画像, class: "label"  %>
            <%= f.attachment_field :profile_image, class: "input" %>
          </div>

          <%= f.submit "更新", class: "button is-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        マイページ
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8">
        <div class="columns is-centered">
          <div class="column is-4">
            <figure class="image is-128x128"  style="margin-left: auto; margin-right: auto;">
              <%= attachment_image_tag @user, :profile_image, fallback: "no-image.png", class: "profile_image is-rounded" %>
            </figure>
          </div>
          <div class="column is-8">
            <table class="table is-fullwidth">
              <tr>
                <td class="is-size-4">
                  <strong><%= @user.username %></trong>
                </td>
                <% if @user.id == current_user.id %>
                <td class="is-size-4">
                  <%= @user.email %>
                </td>
                <td>
                  <%= link_to "編集", edit_user_path(@user), class: "button is-primary"  %>
                </td>
                <% end %>
              </tr>
              <table class="table is-fullwidth">
              <tr>
                <td>
                  <%= @user.profile %>
                </td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>